const char *logo_arch =
"                 █\n"
"                ███\n"
"               █████\n"
"              ███████\n"
"              ▀▀██████\n"
"            ██▄▄ ▀█████\n"
"           █████████████\n"
"          ███████████████\n"
"         █████████████████\n"
"        ███████████████████\n"
"       █████████▀▀▀▀████████\n"
"      ████████▀      ▀███████\n"
"     █████████        ████▀▀██\n"
"    ██████████        ██████▄▄▄\n"
"   ██████████▀        ▀█████████\n"
"  ██████▀▀▀              ▀▀██████\n"
" ███▀▀                       ▀▀███\n"
"▀▀                               ▀▀\n";

const char *alpine_logo =
"       .hddddddddddddddddddddddh.\n"
"      :dddddddddddddddddddddddddd:\n"
"     /dddddddddddddddddddddddddddd/\n"
"    +dddddddddddddddddddddddddddddd+\n"
"  `sdddddddddddddddddddddddddddddddds`\n"
" `ydddddddddddd++hdddddddddddddddddddy`\n"
".hddddddddddd+`  `+ddddh:-sdddddddddddh.\n"
"hdddddddddd+`      `+y:    .sddddddddddh\n"
"ddddddddh+`   `//`   `.`     -sddddddddd\n"
"ddddddh+`   `/hddh/`   `:s-    -sddddddd\n"
"ddddh+`   `/+/dddddh/`   `+s-    -sddddd\n"
"ddd+`   `/o` :dddddddh/`   `oy-    .yddd\n"
"hdddyo+ohddyosdddddddddho+oydddy++ohdddh\n"
".hddddddddddddddddddddddddddddddddddddh.\n"
" `yddddddddddddddddddddddddddddddddddy`\n"
"  `sdddddddddddddddddddddddddddddddds`\n"
"    +dddddddddddddddddddddddddddddd+\n"
"     /dddddddddddddddddddddddddddd/\n"
"      :dddddddddddddddddddddddddd:\n"
"       .hddddddddddddddddddddddh.\n";

const char *arcolinux_logo =
"                   ooo:\n"
"                  yoooo/\n"
"                 yooooooo\n"
"                yooooooooo\n"
"               yooooooooooo\n"
"             .yooooooooooooo\n"
"            .oooooooooooooooo\n"
"           .oooooooarcoooooooo\n"
"          .ooooooooo-oooooooooo\n"
"         .ooooooooo-  oooooooooo\n"
"        :ooooooooo.    :ooooooooo\n"
"       :ooooooooo.      :ooooooooo\n"
"      :oooarcooo         .oooarcooo\n"
"     :ooooooooy           .ooooooooo\n"
"    :ooooooooo   /ooooooooooooooooooo\n"
"   :ooooooooo      .-ooooooooooooooooo.\n"
"  ooooooooo-             -ooooooooooooo.\n"
" ooooooooo-                 .-oooooooooo.\n"
"ooooooooo.                     -ooooooooo\n";

const char *artix_logo =
"                  'o'\n"
"                 'ooo'\n"
"                'ooxoo'\n"
"               'ooxxxoo'\n"
"              'oookkxxoo'\n"
"             'oiioxkkxxoo'\n"
"            ':;:iiiioxxxoo'\n"
"               `'.;::ioxxoo'\n"
"          '-.      `':;jiooo'\n"
"         'oooio-..     `'i:io'\n"
"        'ooooxxxxoio:,.   `'-;'\n"
"       'ooooxxxxxkkxoooIi:-.  `'\n"
"      'ooooxxxxxkkkkxoiiiiiji'\n"
"     'ooooxxxxxkxxoiiii:'`     .i'\n"
"    'ooooxxxxxoi:::'`       .;ioxo'\n"
"   'ooooxooi::'`         .:iiixkxxo'\n"
"  'ooooi:'`                `'';ioxxo'\n"
" 'i:'`                          '':io'\n"
"'`                                   `'\n";

const char *bedrock_logo =
"\\\\\\\\\\\\\\\\\\\\\\\\\n"
" \\\\\\      \\\\\\\n"
"  \\\\\\      \\\\\\\n"
"   \\\\\\      \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\n"
"    \\\\\\                    \\\\\\\n"
"     \\\\\\                    \\\\\\\n"
"      \\\\\\        ______      \\\\\\\n"
"       \\\\\\                   ///\n"
"        \\\\\\                 ///\n"
"         \\\\\\               ///\n"
"          \\\\\\////////////////\n";

const char *ubuntu_logo =
"            .-/+oossssoo+/-.\n"
"        `:+ssssssssssssssssss+:`\n"
"      -+ssssssssssssssssss  ssss+-\n"
"    .ossssssssssssssssss      sssso.\n"
"   /sssssssssss               ssssss/\n"
"  +sssssssss                 ssssssss+\n"
" /ssssssss                    ssssssss/\n"
".ssssssss      ssssssssss      ssssssss.\n"
"+ssss         ssssssssssss      sssssss+\n"
"oss          ssssssssssssss     ssssssso\n"
"oss          ssssssssssssss      sssssso\n"
"+ssss         ssssssssssss      sssssss+\n"
".ssssssss      ssssssssss      ssssssss.\n"
" /ssssssss                    ssssssss/\n"
"  +sssssssss                 ssssssss+\n"
"   /sssssssssss               ssssss/\n"
"    .ossssssssssssssssss      sssso.\n"
"      -+sssssssssssssssss   ssss+-\n"
"        `:+ssssssssssssssssss+:`\n"
"            .-/+oossssoo+/-.\n";

const char *gentoo_logo =
"         -/oyddmdhs+:.\n"
"     -o               +-`\n"
"   -y                    +-\n"
" `o                         /`\n"
" om            hhyyyo         o`\n"
".y           hs++so/s          +`\n"
" oyd           dyooy             d.\n"
"  :o                             Mh\n"
"    .:+                          my\n"
"       /m                        s:\n"
"    `o                         s+`\n"
"  `s                          /.\n"
" /N                        o:`\n"
"+M                       /-\n"
"yM                    /-`\n"
"/h                 /-`\n"
"`/            +/:.`\n"
"  `-//////:--.\n";

const char *generic_logo =
"           @@@%%%%%%%%%@@\n"
"        @@@%%%%%%%%%#######%@@\n"
"      @@@@%%%%%%%######?######%@\n"
"     @@@@%%%%%%%#######:########%@\n"
"   @@@@@%%%%%%#########:??#######%\n"
"   @@@%%%%%####???###?+:??####?###@\n"
"  @@@%%%%%%#?+???###?:+?##??###?##@\n"
"@??%@%%%##????????++:;+?+????????#@\n"
"#  ;?%#?+; ..::+?+ ::;++++++?+???#\n"
"%  :?%;;;:  ....:#+ :;+++????+???@\n"
"#;;+??+++:   ...;##: ;;;++???++?%\n"
"%#%+::++?#+;:::;?##+ ;;;;++??++#\n"
"%?% : :???+?++???######?+;;+??#\n"
"@%# ; ;??;;+ ;???+;;:..::.:+?%\n"
" @???;;?+;;;+ ;:;;......;;;#@\n"
" %##?++?+++;+ ??% @%%@@@@\n"
" @_:?_:+_:_:#%\n";
